Repository openfisca/country-template, pull requests merged in 2018-10, with the labels that each got.

#53 Add editorial content on parameter and variable
  CHANGELOG.md
  openfisca_country_template/parameters/benefits/housing_allowance.yaml
  openfisca_country_template/parameters/benefits/index.yaml
  openfisca_country_template/variables/benefits.py
  setup.py
Labels: flow:team:doing, kind:solution

#55 Document entities
  CHANGELOG.md
  openfisca_country_template/entities.py
  setup.py
Labels: flow:team:doing

#57 Introduce postal_code variable of type string
  CHANGELOG.md
  openfisca_country_template/variables/housing.py
  setup.py
Labels: flow:team:doing

#59 Test against packaged version
  .circleci/config.yml
  .circleci/has-functional-changes.sh
  .circleci/publish-python-package.sh
  CHANGELOG.md
  LICENSE
  MANIFEST.in
  Makefile
  setup.cfg
  setup.py
Labels: flow:team:doing, kind:improvement

#63 Cleanup CircleCI config
  .circleci/config.yml
  .circleci/publish-python-package.sh
  CHANGELOG.md
  setup.py
Labels: flow:team:doing, kind:improvement
